
import { Question } from './types';

export const THEME = {
  bg: '#FFFFFF',
  bgCard: '#FFFFFF',
  bgSecondary: '#F8FAFC',
  bgGlass: 'rgba(241, 245, 249, 0.5)',
  border: 'rgba(0, 0, 0, 0.06)',
  borderActive: 'rgba(16, 185, 129, 0.3)', 
  accent: '#10B981', 
  accentDim: 'rgba(16, 185, 129, 0.08)',
  accentGlow: '0 10px 25px rgba(16, 185, 129, 0.1)',
  gold: '#F59E0B',
  goldDim: 'rgba(245, 158, 11, 0.08)',
  red: '#EF4444',
  redDim: 'rgba(239, 68, 68, 0.08)',
  amber: '#F59E0B',
  amberDim: 'rgba(245, 158, 11, 0.08)',
  blue: '#3B82F6',
  blueDim: 'rgba(59, 130, 246, 0.08)',
  text: '#0F172A', 
  textMuted: '#64748B', 
  textDim: '#94A3B8', 
  fontDisplay: "'IBM Plex Sans Arabic', 'Tajawal', sans-serif",
  fontBody: "'IBM Plex Sans Arabic', 'Tajawal', sans-serif",
};

export const QUESTIONS: Question[] = [
  {
    id: "sector",
    step: 1,
    icon: "Layers",
    label: "محرك تقاطع القطاعات (Cross-Sector Innovation)",
    sublabel: "اختر قطاعين أو أكثر لنقوم باكتشاف 'المحيط الأزرق' الخاص بمشروعك الهجين.",
    type: "cards",
    multi: true,
    options: [
      { val: "ecommerce", icon: "ShoppingBag", title: "متجر إلكتروني", desc: "بيع منتجات مادية أو رقمية عبر الإنترنت" },
      { val: "saas", icon: "Settings", title: "برمجيات SaaS", desc: "خدمة باشتراك شهري تحل مشكلة محددة" },
      { val: "marketplace", icon: "Link", title: "منصة وسيطة", desc: "ربط البائعين بالمشترين أو مقدمي الخدمة" },
      { val: "delivery", icon: "Truck", title: "لوجستيات وتوصيل", desc: "تحريك الأشياء من مكان لآخر بكفاءة" },
      { val: "fintech", icon: "CreditCard", title: "تقنية مالية", desc: "مدفوعات، تمويل، استثمار ذكي" },
      { val: "education", icon: "GraduationCap", title: "تعليم وتدريب", desc: "نقل المعرفة والمهارات بطريقة مبتكرة" },
      { val: "health", icon: "HeartPulse", title: "صحة ورعاية", desc: "عيادة، تطبيق صحي، منتج طبي" },
      { val: "local", icon: "MapPin", title: "خدمة محلية", desc: "أعمال تخدم منطقة جغرافية محددة مباشرةً" },
    ],
  },
  {
    id: "problem",
    step: 2,
    icon: "Target",
    label: "ما المشكلة التي تحلها بالضبط؟ (Jobs to be Done)",
    sublabel: "أفضل الأعمال تولد من ألم حقيقي — صف 'المهمة' التي سيكلفك العميل بها.",
    type: "textarea_choice",
    placeholder: "مثال: أريد أن أقتل الشعور بالإحباط عند البحث عن قطع غيار نادرة...",
    options: [
      { val: "functional", icon: "Settings2", label: "مهمة وظيفية (توفير وقت، جهد، مال)" },
      { val: "emotional", icon: "Heart", label: "مهمة عاطفية (شعور بالأمان، الهدوء، التميز)" },
      { val: "social", icon: "UsersRound", label: "مهمة اجتماعية (الوجاهة، الانتماء لمجتمع معين)" },
      { val: "copy_improve", icon: "Zap", label: "تطوير نموذج موجود ولكن بمستويات أعلى" },
    ],
  },
  {
    id: "empathy_data",
    step: 3,
    icon: "Heart",
    label: "خريطة التعاطف (Behavioral Persona)",
    sublabel: "لنفكر بعقل عميلك؛ ما هي محركاته اللحظية؟",
    type: "empathy_map",
    options: [
      { val: "status", label: "ماذا يرى؟ (يسعى للوجاهة، يرى المنافسين ينجحون)" },
      { val: "fear", label: "ماذا يخشى؟ (الفشل، ضياع الفرص، التقييم السيء)" },
      { val: "efficiency", label: "ماذا يسمع؟ (نصائح تقنية، ضجيج السوق)" },
      { val: "pains", label: "ما هي آلامه؟ (تعقيد الإجراءات، ارتفاع التكاليف)" },
    ],
  },
  {
    id: "competition",
    step: 4,
    icon: "SearchCode",
    label: "الذكاء التنافسي (Competitive Intelligence)",
    sublabel: "من يسرق نومك؟ وكيف ستتفوق عليه بضربة استباقية؟",
    type: "competition_map",
    options: [
      { val: "big_clunky", icon: "Castle", title: "عمالقة بطيئون", desc: "شركات كبيرة لكنها تفتقد للمرونة والسرعة" },
      { val: "niche_players", icon: "Sword", title: "منافسون متخصصون", desc: "لاعبون في زوايا محددة لكنهم لا يغطون الكل" },
      { val: "traditional", icon: "Home", title: "بدائل تقليدية", desc: "الناس يحلون المشكلة بطرق قديمة غير فعالة" },
      { val: "unsolved", icon: "Compass", title: "سوق مهمل", desc: "المشكلة موجودة ولا أحد يحاول حلها فعلياً" },
    ],
    followup: {
      label: "محرك التميز (The Moat Strategy):",
      options: ["⚡ سرعة استجابة فائقة", "🤖 تجربة مدعومة بالـ AI", "🎨 تصميم يتمحور حول العاطفة", "🌍 وصول محلي بدقة عالمية"],
    },
  },
  {
    id: "resources",
    step: 5,
    icon: "Gauge",
    label: "حساب تكلفة الفرصة البديلة (Opportunity Cost)",
    sublabel: "مواردك محددة؛ لنرى أين يجب أن تستثمر وقتك لتعظيم الربح.",
    type: "resources_check",
    items: [
      { id: "budget_range", icon: "Coins", label: "السيولة النقدية المتاحة", options: ["$0-$500", "$500-$2,000", "$2,000-$10,000", "+$10,000"] },
      { id: "time_cost", icon: "Clock", label: "استثمارك الزمني (تعطيل مهام أخرى)", options: ["أقل من 10 ساعات", "10-25 ساعة", "25-40 ساعة (تفرغ جزئي)", "40+ ساعة (تفرغ كامل)"] },
      { id: "tech_skills", icon: "Settings", label: "مستوى الكفاءة التقنية", options: ["إداري فقط", "تقني أساسي", "خبير في بناء الأنظمة", "محترف AI / برمجيات"] },
      { id: "market_access", icon: "Megaphone", label: "قدرتك على الوصول لـ 100 عميل", options: ["صعبة جداً", "عبر إعلانات ممولة", "عبر علاقات شخصية", "أملك قاعدة بيانات فعالة"] },
    ],
  },
  {
    id: "validation",
    step: 6,
    icon: "Rocket",
    label: "مقياس الجاهزية الميدانية",
    sublabel: "التحقق الميداني هو الفرق بين 'حلم' و 'حقيقة'.",
    type: "validation_scale",
    options: [
      { val: "zero", icon: "FileQuestion", title: "مرحلة التلخيص", desc: "الفكرة لا تزال نصوصاً في مذكرتي", score: 1 },
      { val: "interviewed", icon: "Mic2", title: "مقابلات حية", desc: "سألت 10 أشخاص مجهولين وأكدوا الأهمية", score: 3 },
      { val: "prototype", icon: "LayoutTemplate", title: "تم بناء النموذج", desc: "لدي نموذج أولي بسيط (MVP) أطلقه غداً", score: 4 },
      { val: "preorder", icon: "Zap", title: "طلبات مسبقة", desc: "لدي التزامات مالية أو تسجيلات فعلية", score: 5 },
    ],
  },
  {
    id: "goal_matrix",
    step: 7,
    icon: "Goal",
    label: "مصفوفة التأثير والنمو",
    sublabel: "وضوحك في الهدف يحدد ما إذا كنت تبني 'وظيفة' أم 'إمبراطورية'.",
    type: "goal_matrix",
    goals: [
      { id: "target_revenue", label: "🎯 الطموح الإيرادي (شهرياً)", options: ["$1k-$5k", "$5k-$20k (استقلال مالي)", "$20k-$100k (كيان مؤسسي)", "+$100k"] },
      { id: "exit_path", label: "🚀 المسار الاستراتيجي", options: ["Lifestyle — دخل مستقر", "Scalable — نمو للبيع لاحقاً", "Enterprise — بناء إرث طويل", "Social — أثر مجتمعي أولاً"] },
      { id: "risk_tolerance", label: "⚠️ التحمل للمخاطر", options: ["محافظ جداً", "متوازن", "مغامر محسوب", "نمو متطرف (Blitzscaling)"] },
    ],
  },
  {
    id: "biggest_fear",
    step: 8,
    icon: "ShieldAlert",
    label: "مصفوفة الاستعداد الاستباقي",
    sublabel: "لنواجه المخاوف الآن لنحولها إلى نقاط قوة في خطة الطوارئ.",
    type: "fear_select",
    multi: true,
    options: [
      { val: "liquidity", icon: "Coins", label: "أزمة سيولة مفاجئة" },
      { val: "retention", icon: "UserMinus", label: "خسارة العملاء بعد أول شهر" },
      { val: "competitor_move", icon: "Zap", label: "تحرك عدواني من منافس كبير" },
      { val: "execution_gap", icon: "Settings2", label: "فجوة بين الرؤية والتنفيذ" },
      { val: "legal_walls", icon: "Gavel", label: "عوائد قانونية أو تراخيص" },
      { val: "wrong_market", icon: "SearchX", label: "اكتشاف أن السوق أصغر مما ظننت" },
    ],
  },
];
